name: Build Python

on:
  push:
    paths:
      - 'python/**'
      - '!python/binarypuzzle.exe'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Build Python executable

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Create build
        run: |
          cd python
          pyinstaller main.py --onefile --name binarypuzzle --hidden-import colorama --icon ../images/binarypuzzle.png
      - name: Run python file
        run: |
          cd python
          python ../.github/workflows/buildpython.py
